name: Meal Planner API
slug: meal_planner_api
description: FastAPI backend for the Home Assistant Meal Planner
version: "1.0.0"
arch:
  - amd64
startup: services
init: false

host_network: true

map:
  - data:rw
  - homeassistant_config:rw

options: {}
schema: {}

log_level: info
